#!/bin/sh
input=$(cat)

cwd=$(echo "$input"      | jq -r '.cwd // .workspace.current_dir // ""')
model=$(echo "$input"    | jq -r '.model.display_name // ""')
used_pct=$(echo "$input" | jq -r '.context_window.used_percentage // empty')
five_h_used=$(echo "$input" | jq -r '.rate_limits.five_hour.used_percentage // empty')
week_used=$(echo "$input"   | jq -r '.rate_limits.seven_day.used_percentage // empty')
five_h_reset=$(echo "$input" | jq -r '.rate_limits.five_hour.resets_at // empty')
week_reset=$(echo "$input"   | jq -r '.rate_limits.seven_day.resets_at // empty')

dir=$(basename "$cwd")

git_branch=""
if git -C "$cwd" rev-parse --is-inside-work-tree --no-optional-locks > /dev/null 2>&1; then
  branch=$(git -C "$cwd" --no-optional-locks symbolic-ref --short HEAD 2>/dev/null)
  if [ -n "$branch" ]; then
    dirty=$(git -C "$cwd" --no-optional-locks status --porcelain 2>/dev/null)
    if [ -n "$dirty" ]; then git_branch="${branch}*"
    else git_branch="${branch}"
    fi
  fi
fi

# ---------------------------------------------------------------------------
# Palette is generated by tinty hook (see ~/.config/tinted-theming/).
# Hardcoded fallback applies if the file is missing.
# ---------------------------------------------------------------------------
PALETTE_FILE="$HOME/dotfiles/.config/tinted-theming/palette.sh"
if [ -f "$PALETTE_FILE" ]; then
  . "$PALETTE_FILE"
  CRUST="$PAL_BASE00_RGB"
  BG_RED="$PAL_BASE08_RGB"      # dir
  BG_PEACH="$PAL_BASE09_RGB"    # git branch
  BG_YELLOW="$PAL_BASE0A_RGB"   # model
  BG_LAVENDER="$PAL_BASE0F_RGB" # context window
  BG_GREEN="$PAL_BASE0B_RGB"    # rate ≥80%
  BG_ORANGE="$PAL_BASE09_RGB"   # rate 40-79%
  BG_ALERT="$PAL_BASE08_RGB"    # rate <40%
else
  CRUST="17;17;27"
  BG_RED="243;139;168"
  BG_PEACH="250;179;135"
  BG_YELLOW="249;226;175"
  BG_LAVENDER="180;190;254"
  BG_GREEN="166;227;161"
  BG_ORANGE="250;179;135"
  BG_ALERT="243;139;168"
fi

# Nerd Font glyphs via UTF-8 hex (avoids file-encoding issues)
SEP=$(printf '\xee\x82\xb0')          # U+E0B0  ► powerline divider (between segments)
LEFT_CAP=$(printf '\xee\x82\xb6')    # U+E0B6   rounded left cap
RIGHT_CAP=$(printf '\xee\x82\xb4')   # U+E0B4   rounded right cap
ICON_BRANCH=$(printf '\xee\x82\xa0') # U+E0A0   git branch
ICON_CTX=$(printf '\xef\x83\xa4')    # U+F0E4   gauge/dashboard (context)
ICON_CLOCK=$(printf '\xef\x80\x97')  # U+F017   clock (5h)
ICON_CAL=$(printf '\xef\x81\xb3')    # U+F073   calendar (7d)

# ---------------------------------------------------------------------------
# Segment engine — connected powerline style, matching Starship
# ---------------------------------------------------------------------------
_prev_bg=""

seg() {
  _bg=$1; _content=$2; _fg=${3:-$CRUST}
  if [ -n "$_prev_bg" ]; then
    printf '\033[38;2;%sm\033[48;2;%sm%s' "$_prev_bg" "$_bg" "$SEP"
  else
    printf '\033[0m\033[38;2;%sm%s\033[48;2;%sm' "$_bg" "$LEFT_CAP" "$_bg"
  fi
  printf '\033[38;2;%sm%s' "$_fg" "$_content"
  _prev_bg=$_bg
}

endcap() {
  [ -n "$_prev_bg" ] && printf '\033[0m\033[38;2;%sm%s\033[0m' "$_prev_bg" "$RIGHT_CAP"
  printf '\n'
}

rate_bg() {
  if   [ "$1" -ge 80 ]; then rl_bg="$BG_GREEN"
  elif [ "$1" -ge 40 ]; then rl_bg="$BG_ORANGE"
  else                        rl_bg="$BG_ALERT"
  fi
}

# Blend an "R;G;B" triplet toward white by factor f (0..1) — the paler inset
# capsule background for the rollover counter.
lighten() {
  awk -v c="$1" -v f="$2" 'BEGIN { split(c, a, ";")
    printf "%d;%d;%d", a[1]+(255-a[1])*f, a[2]+(255-a[2])*f, a[3]+(255-a[3])*f }'
}

# Blend triplet $1 toward triplet $2 by factor f — softens the rollover text so
# it reads lighter than the bold percentage.
mix() {
  awk -v x="$1" -v y="$2" -v f="$3" 'BEGIN { split(x, a, ";"); split(y, b, ";")
    printf "%d;%d;%d", a[1]+(b[1]-a[1])*f, a[2]+(b[2]-a[2])*f, a[3]+(b[3]-a[3])*f }'
}

# Time until a rate-limit window rolls over, as plain text in whole hours
# ("<1h" if less than an hour).
now=$(date +%s)
reset_label() {
  rl_label=""
  [ -z "$1" ] && return
  _delta=$(( $1 - now ))
  if   [ "$_delta" -le 0 ];    then rl_label="0h"
  elif [ "$_delta" -lt 3600 ]; then rl_label="<1h"
  else                              rl_label="$(( (_delta + 1800) / 3600 ))h"
  fi
}

# Draw a rate-limit window: {icon}{remaining%} on the rate-colored background,
# and — when a reset time is known — the rollover countdown inside a paler,
# rounded inset "capsule" so it reads as a sub-element of the same segment.
rate_segment() {
  _icon=$1; _rem=$2; _reset=$3
  rate_bg "$_rem"
  reset_label "$_reset"
  if [ -n "$rl_label" ]; then
    _light=$(lighten "$rl_bg" 0.5)
    _soft=$(mix "$CRUST" "$_light" 0.45)
    _cap=$(printf '\033[38;2;%sm%s\033[48;2;%sm\033[38;2;%sm%s\033[48;2;%sm\033[38;2;%sm%s\033[48;2;%sm' \
      "$_light" "$LEFT_CAP" "$_light" "$_soft" "$rl_label" "$rl_bg" "$_light" "$RIGHT_CAP" "$rl_bg")
    seg "$rl_bg" " ${_icon} ${_rem}% ${_cap} "
  else
    seg "$rl_bg" " ${_icon} ${_rem}% "
  fi
}

# ---------------------------------------------------------------------------
# Build the statusline
# ---------------------------------------------------------------------------
seg "$BG_RED" " ${dir} "

[ -n "$git_branch" ] && seg "$BG_PEACH" " ${ICON_BRANCH} ${git_branch} "

[ -n "$model" ] && seg "$BG_YELLOW" " ${model} "

if [ -n "$used_pct" ]; then
  ctx_pct=$(printf "%.0f" "$used_pct")
  seg "$BG_LAVENDER" " ${ICON_CTX} ${ctx_pct}% "
fi

[ -n "$five_h_used" ] && \
  rate_segment "$ICON_CLOCK" "$(echo "$five_h_used" | awk '{printf "%.0f", 100 - $1}')" "$five_h_reset"

[ -n "$week_used" ] && \
  rate_segment "$ICON_CAL" "$(echo "$week_used" | awk '{printf "%.0f", 100 - $1}')" "$week_reset"

endcap
