#!/usr/bin/env bash
# Generated theme apply hook — invoked by tinty after a scheme is applied.
# Writes color outputs for: Ghostty theme file, Starship palette block, Claude statusline palette.
# Reads $TINTY_SCHEME_PALETTE_BASE{00..0F}_HEX_{R,G,B} env vars.

set -e

DOTFILES="/Users/adamzajac/dotfiles"

# Build hex colors b00..b0F (e.g. "1e1e2e") from RGB hex components.
for i in 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F; do
  rvar="TINTY_SCHEME_PALETTE_BASE${i}_HEX_R"
  gvar="TINTY_SCHEME_PALETTE_BASE${i}_HEX_G"
  bvar="TINTY_SCHEME_PALETTE_BASE${i}_HEX_B"
  eval "b${i}=\${${rvar}}\${${gvar}}\${${bvar}}"
done

# Extended base24 colors b10..b17 — only set in base24 schemes.
# When the scheme is base16-only, fall back to the closest base16 index per
# the base24 → ANSI bright-slot mapping.
#   base10 (darker bg)   → base01
#   base11 (darkest bg)  → base00
#   base12 (bright red)  → base08
#   base13 (bright yel)  → base0A
#   base14 (bright grn)  → base0B
#   base15 (bright cyn)  → base0C
#   base16 (bright blu)  → base0D
#   base17 (bright mag)  → base0E
for pair in "10:01" "11:00" "12:08" "13:0A" "14:0B" "15:0C" "16:0D" "17:0E"; do
  i="${pair%:*}"
  fb="${pair#*:}"
  rvar="TINTY_SCHEME_PALETTE_BASE${i}_HEX_R"
  gvar="TINTY_SCHEME_PALETTE_BASE${i}_HEX_G"
  bvar="TINTY_SCHEME_PALETTE_BASE${i}_HEX_B"
  if [ -n "${!rvar:-}" ]; then
    eval "b${i}=\${${rvar}}\${${gvar}}\${${bvar}}"
  else
    eval "b${i}=\${b${fb}}"
  fi
done

# RGB triplets "R;G;B" used by ANSI escapes (Claude statusline).
for i in 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F; do
  rvar="TINTY_SCHEME_PALETTE_BASE${i}_RGB_R"
  gvar="TINTY_SCHEME_PALETTE_BASE${i}_RGB_G"
  bvar="TINTY_SCHEME_PALETTE_BASE${i}_RGB_B"
  eval "rgb${i}=\"\${${rvar}};\${${gvar}};\${${bvar}}\""
done

# ----------------------------------------------------------------------------
# 1. Ghostty theme file
# ----------------------------------------------------------------------------
GHOSTTY_THEME="${DOTFILES}/.config/ghostty/themes/tinted"
mkdir -p "$(dirname "$GHOSTTY_THEME")"
cat > "$GHOSTTY_THEME" <<EOF
# Auto-generated by tinty hook for scheme: ${TINTY_SCHEME_ID}
# Do not edit by hand — re-run \`tinty apply <scheme>\` to regenerate.

background = #${b00}
foreground = #${b05}
cursor-color = #${b05}
selection-background = #${b02}
selection-foreground = #${b05}

palette = 0=#${b00}
palette = 1=#${b08}
palette = 2=#${b0B}
palette = 3=#${b0A}
palette = 4=#${b0D}
palette = 5=#${b0E}
palette = 6=#${b0C}
palette = 7=#${b05}
palette = 8=#${b03}
palette = 9=#${b12}
palette = 10=#${b14}
palette = 11=#${b13}
palette = 12=#${b16}
palette = 13=#${b17}
palette = 14=#${b15}
palette = 15=#${b07}
EOF

# ----------------------------------------------------------------------------
# 2. Starship palette — replace block between markers in starship.toml
# ----------------------------------------------------------------------------
STARSHIP="${DOTFILES}/.config/starship.toml"
PALETTE_TMP="$(mktemp)"
cat > "$PALETTE_TMP" <<EOF
# === BEGIN TINTED PALETTE ===
# Auto-generated by tinty hook for scheme: ${TINTY_SCHEME_ID}
# Do not edit by hand — re-run \`tinty apply <scheme>\` to regenerate.
[palettes.tinted]
# Catppuccin-name aliases for compatibility with existing styles.
red      = "#${b08}"
peach    = "#${b09}"
yellow   = "#${b0A}"
green    = "#${b0B}"
teal     = "#${b0C}"
sapphire = "#${b16}"
blue     = "#${b0D}"
mauve    = "#${b0E}"
lavender = "#${b07}"
crust    = "#${b00}"
text     = "#${b05}"
# Raw base16 indices (for direct base16 references).
base00 = "#${b00}"
base01 = "#${b01}"
base02 = "#${b02}"
base03 = "#${b03}"
base04 = "#${b04}"
base05 = "#${b05}"
base06 = "#${b06}"
base07 = "#${b07}"
base08 = "#${b08}"
base09 = "#${b09}"
base0A = "#${b0A}"
base0B = "#${b0B}"
base0C = "#${b0C}"
base0D = "#${b0D}"
base0E = "#${b0E}"
base0F = "#${b0F}"
# Extended base24 indices (fall back to base16 when scheme is base16-only).
base10 = "#${b10}"
base11 = "#${b11}"
base12 = "#${b12}"
base13 = "#${b13}"
base14 = "#${b14}"
base15 = "#${b15}"
base16 = "#${b16}"
base17 = "#${b17}"
# === END TINTED PALETTE ===
EOF

# Replace the BEGIN..END block in starship.toml with contents of $PALETTE_TMP.
awk -v paletteFile="$PALETTE_TMP" '
  /^# === BEGIN TINTED PALETTE ===$/ {
    while ((getline line < paletteFile) > 0) print line
    close(paletteFile)
    skipping = 1
    next
  }
  /^# === END TINTED PALETTE ===$/ {
    skipping = 0
    next
  }
  !skipping { print }
' "$STARSHIP" > "${STARSHIP}.tmp" && mv "${STARSHIP}.tmp" "$STARSHIP"

rm -f "$PALETTE_TMP"

# ----------------------------------------------------------------------------
# 3. Claude statusline palette — sourceable shell vars
# ----------------------------------------------------------------------------
PALETTE_SH="${DOTFILES}/.config/tinted-theming/palette.sh"
cat > "$PALETTE_SH" <<EOF
# Auto-generated by tinty hook for scheme: ${TINTY_SCHEME_ID}
# Do not edit by hand — re-run \`tinty apply <scheme>\` to regenerate.

# Hex (no #-prefix)
PAL_BASE00_HEX="${b00}"
PAL_BASE05_HEX="${b05}"
PAL_BASE08_HEX="${b08}"
PAL_BASE09_HEX="${b09}"
PAL_BASE0A_HEX="${b0A}"
PAL_BASE0B_HEX="${b0B}"
PAL_BASE0D_HEX="${b0D}"
PAL_BASE0F_HEX="${b0F}"

# ANSI RGB triplets "R;G;B"
PAL_BASE00_RGB="${rgb00}"
PAL_BASE05_RGB="${rgb05}"
PAL_BASE08_RGB="${rgb08}"
PAL_BASE09_RGB="${rgb09}"
PAL_BASE0A_RGB="${rgb0A}"
PAL_BASE0B_RGB="${rgb0B}"
PAL_BASE0C_RGB="${rgb0C}"
PAL_BASE0D_RGB="${rgb0D}"
PAL_BASE0F_RGB="${rgb0F}"
EOF

echo "tinty hook: applied $TINTY_SCHEME_ID — wrote ghostty/starship/claude palettes"
