# Vellum dark - black card, surface relief only.
OMNI_THEME="np-vellum-dark"
OMNI_FONT="Lekton Nerd Font Mono"
OMNI_FONT_SIZE=21
OMNI_MENU_COLS=38
OMNI_FILL_INSET=10
OMNI_ROW_PAD="30%"
OMNI_PADDING="0,1"
OMNI_BORDER_SLOT=18
OMNI_BORDER_STYLE="sharp"
OMNI_INPUT_BORDER="bottom"
OMNI_SHADER="np-vellum-dark.glsl"
OMNI_FRAME="boxed"
OMNI_OPACITY=0.95
OMNI_BLUR=20
OMNI_TERM_SIZE="46%,96%"
