# Auto-generated by tinty hook for scheme: base24-catppuccin-mocha
# Do not edit by hand — re-run `tinty apply <scheme>` to regenerate.

# Hex (no #-prefix)
PAL_BASE00_HEX="1e1e2e"
PAL_BASE05_HEX="cdd6f4"
PAL_BASE08_HEX="f38ba8"
PAL_BASE09_HEX="fab387"
PAL_BASE0A_HEX="f9e2af"
PAL_BASE0B_HEX="a6e3a1"
PAL_BASE0D_HEX="89b4fa"
PAL_BASE0F_HEX="f2cdcd"

# ANSI RGB triplets "R;G;B"
PAL_BASE00_RGB="30;30;46"
PAL_BASE05_RGB="205;214;244"
PAL_BASE08_RGB="243;139;168"
PAL_BASE09_RGB="250;179;135"
PAL_BASE0A_RGB="249;226;175"
PAL_BASE0B_RGB="166;227;161"
PAL_BASE0C_RGB="148;226;213"
PAL_BASE0D_RGB="137;180;250"
PAL_BASE0F_RGB="242;205;205"
